

import { DEFAULT_GEMINI_LITE_MODEL } from '../config/models.js';
import { FileSummary as PaperSummary, InfrastructureContext as InvestigationContext } from '../novum_core/types.js';
import { GeminiClient } from '../services/geminiClient.js';
import { getAssetString, replaceRuntimePlaceholders } from '../services/promptManager.js';
import { isAutoGenerated } from './paperVersionDiff.js';
import { removeBacktickFences, repairTruncatedJsonArray, toKebabCase } from './markdownUtils.js';
import { RelevantPaperFile, analyzeRelevantDocumentsForInvestigation } from './paperDocumentAnalyzer.js';


export const MAX_ANALYSIS_FILE_SIZE_BYTES = 102400;


export const HAS_FUNCTIONS_EXTENSIONS = new Set([
  '.py', '.r', '.rmd', '.jl', '.m', '.ipynb',
  '.ts', '.js', '.tsx', '.jsx',
  '.java', '.c', '.cpp', '.cs', '.go',
]);


export const RESEARCH_DOCUMENT_EXTENSIONS = new Set([
  
  '.pdf', '.docx', '.doc', '.tex', '.md', '.txt', '.rtf',
  
  '.csv', '.tsv', '.xlsx', '.xls', '.json', '.xml', '.yaml', '.yml',
  
  '.py', '.r', '.rmd', '.jl', '.m', '.ipynb', '.sas', '.do',
  
  '.spv', '.sav',
  
  '.html', '.htm',
  
  '.ini', '.toml', '.cfg', '.env',
]);


export const RED_FLAG_KEYWORDS = new Set([
  'paper mill', 'tortured phrase', 'pubpeer', 'expressions of concern',
  'retracted', 'retraction', 'fabricated', 'manipulation', 'duplicate image',
  'data unavailable', 'ethics approval missing', 'conflict of interest undisclosed',
]);

function getBasename(filename: string): string {
  const lastSlash = Math.max(filename.lastIndexOf('/'), filename.lastIndexOf('\\'));
  return filename.substring(lastSlash + 1);
}

export function getFileExtension(filename: string): string {
  const base    = getBasename(filename);
  const lastDot = base.lastIndexOf('.');
  if (lastDot === -1) return 'no-extension';
  if (lastDot === 0)  return base;
  return base.substring(lastDot).toLowerCase();
}

const paperAnalysis: Map<string, PaperSummary> = new Map();
let investigationTitle: string | undefined;

let investigationRelevantDocs: RelevantPaperFile[] = [];
let dynamicallyAddedDocs: Set<string> = new Set();


export async function analysePapers(
  fileMap:       Map<string, string>,
  binaryFileMap: Map<string, string> = new Map(),
  geminiClient?: GeminiClient
): Promise<void> {
  paperAnalysis.clear();
  investigationRelevantDocs = [];
  dynamicallyAddedDocs.clear();

  for (const filename of fileMap.keys()) {
    paperAnalysis.set(filename, { filename });
  }
  for (const filename of binaryFileMap.keys()) {
    paperAnalysis.set(filename, { filename, description: 'Binary / supplementary file.' });
  }

  if (geminiClient) await refreshInvestigationTitle(geminiClient);
}

export function removePaperEntry(filename: string): void {
  const summary = paperAnalysis.get(filename) ?? { filename };
  summary.description = '---DELETED---';
  summary.relatedFiles = '';
  paperAnalysis.set(filename, summary);

  const taskEntry = investigationRelevantDocs.find(f => f.filename === filename);
  if (taskEntry) taskEntry.description = '---DELETED---';

  for (const s of paperAnalysis.values()) {
    if (s.relatedFiles) {
      s.relatedFiles = s.relatedFiles.split('\n').filter(f => f.trim() !== filename).join('\n');
    }
  }
}

export async function updatePaperEntry(
  filename:     string,
  fileMap:      Map<string, string>,
  geminiClient?: GeminiClient,
  explicitUpdate?: PaperSummary,
  skipAnalysis: boolean = false
): Promise<PaperSummary | undefined> {
  if (isAutoGenerated(filename)) {
    const s: PaperSummary = { filename, description: 'Auto-generated file.', relatedFiles: '' };
    paperAnalysis.set(filename, s);
    return s;
  }

  if (explicitUpdate) { paperAnalysis.set(filename, explicitUpdate); return explicitUpdate; }
  if (skipAnalysis) return paperAnalysis.get(filename);
  if (!geminiClient) {
    const s: PaperSummary = { filename };
    paperAnalysis.set(filename, s);
    return s;
  }

  const filesToProcess = new Set<string>([filename]);
  const existing = paperAnalysis.get(filename);
  if (existing?.relatedFiles)
    existing.relatedFiles.split('\n').map(f => f.trim()).filter(Boolean).forEach(f => filesToProcess.add(f));

  let results: Map<string, PaperSummary> | undefined;
  try { results = await doPaperAnalysis(filesToProcess, fileMap, geminiClient); }
  catch { return undefined; }

  if (!results) return undefined;

  const updated = results.get(filename);
  if (updated) {
    paperAnalysis.set(filename, updated);
    const taskEntry = investigationRelevantDocs.find(f => f.filename === filename);
    if (taskEntry && updated.description) taskEntry.description = updated.description;
  }
  for (const [fn, s] of results.entries()) {
    if (!paperAnalysis.has(fn)) paperAnalysis.set(fn, s);
  }

  try { if (results.size > paperAnalysis.size) await refreshInvestigationTitle(geminiClient); } catch {}
  return updated;
}

export async function analyseAndSetInvestigationRelevantDocuments(
  investigationDescription: string,
  assumptions:  string,
  fileMap:      Map<string, string>,
  binaryFileMap: Map<string, string>,
  infrastructureContext: InvestigationContext,
  geminiClient: GeminiClient,
  sendMessage:  (msg: string) => void,
  image?:       string,
  imageMimeType?: string
): Promise<void> {
  investigationRelevantDocs = await analyzeRelevantDocumentsForInvestigation(
    investigationDescription, assumptions, fileMap, binaryFileMap,
    infrastructureContext, geminiClient, sendMessage, image, imageMimeType,
  );
  dynamicallyAddedDocs.clear();
}

export function addDynamicallyRelevantDocument(filename: string): void {
  if (!filename) return;
  if (investigationRelevantDocs.some(f => f.filename === filename)) return;
  dynamicallyAddedDocs.add(filename);
}


export function getInvestigationRelevantDescriptions(): string {
  const lines: string[] = [];

  if (investigationRelevantDocs.length > 0) {
    lines.push('## Investigation Documents');
    lines.push('**Likely Relevant to This Investigation:**');
    for (const doc of investigationRelevantDocs) {
      lines.push(doc.filename);
      lines.push(doc.description ? `"${doc.description}"` : '---No description available---');
    }
  }

  const dynamic = [...dynamicallyAddedDocs].filter(fn => !investigationRelevantDocs.some(f => f.filename === fn));
  if (dynamic.length > 0) {
    lines.push('');
    lines.push('**Documents Read / Analysed During This Investigation:**');
    dynamic.sort().forEach(fn => {
      lines.push(fn);
      const s = paperAnalysis.get(fn);
      if (s?.description) lines.push(`> ${s.description}`);
      if (s?.redFlags?.length) lines.push(`> ?? Red flags: ${s.redFlags.join(', ')}`);
    });
  }

  const folderPaths = new Set<string>();
  for (const fp of paperAnalysis.keys()) {
    fp.split('/').slice(0, -1).reduce((acc, part) => {
      const p = acc ? `${acc}/${part}` : part;
      folderPaths.add(p);
      return p;
    }, '');
  }
  if (folderPaths.size > 0) {
    lines.push('');
    lines.push('**Corpus Folder Structure:**');
    [...folderPaths].sort().forEach(f => lines.push(`* ${f}/`));
  }

  const allRelevant = new Set([
    ...investigationRelevantDocs.map(f => f.filename),
    ...dynamicallyAddedDocs,
  ]);
  const extCounts = new Map<string, number>();
  for (const { filename } of paperAnalysis.values()) {
    if (!filename || allRelevant.has(filename)) continue;
    const ext = getFileExtension(filename);
    extCounts.set(ext, (extCounts.get(ext) ?? 0) + 1);
  }
  if (extCounts.size > 0) {
    lines.push('');
    lines.push('**Other Files in Corpus (by extension):**');
    [...extCounts.keys()].sort().forEach(ext => {
      const n = extCounts.get(ext)!;
      lines.push(ext === 'no-extension' ? `* ${n} file(s) with no extension` : `* ${n} ${ext} file(s)`);
    });
  }

  const final = lines.join('\n').trim();
  if (!final && paperAnalysis.size > 0) return '## All documents in the corpus were listed as relevant.';
  return final || '--No documents available--';
}

export function getPaperAnalysis(filename: string): PaperSummary | undefined {
  return paperAnalysis.get(filename);
}


export function getPaperDescriptions(): string {
  const lines:          string[] = [];
  const researchDocs:   PaperSummary[] = [];
  const otherExtCounts  = new Map<string, number>();

  for (const summary of paperAnalysis.values()) {
    if (!summary?.filename) continue;
    const ext = getFileExtension(summary.filename);
    if (RESEARCH_DOCUMENT_EXTENSIONS.has(ext)) researchDocs.push(summary);
    else otherExtCounts.set(ext, (otherExtCounts.get(ext) ?? 0) + 1);
  }

  if (researchDocs.length > 0) {
    lines.push('## Research Documents & Data Files');
    researchDocs.sort((a, b) => a.filename.localeCompare(b.filename));
    for (const s of researchDocs) {
      lines.push(s.filename);
      if (s.description?.trim()) lines.push(s.description);
      if (s.redFlags?.length)    lines.push(`?? Red flags: ${s.redFlags.join(', ')}`);
      lines.push('');
    }
  }

  if (otherExtCounts.size > 0) {
    lines.push('## Other Corpus Files');
    [...otherExtCounts.keys()].sort().forEach(ext => {
      const n = otherExtCounts.get(ext)!;
      lines.push(ext === 'no-extension' ? `* ${n} file(s) with no extension` : `* ${n} ${ext} file(s)`);
    });
    lines.push('');
  }

  return lines.join('\n').trim();
}

export function findInDocuments(query: string, fileMap: Map<string, string>): string[] {
  return [...fileMap.entries()]
    .filter(([path, content]) => path.includes(query) || content.includes(query))
    .map(([path]) => path);
}

export function getDocumentListString(
  fileContentMap?: Map<string, unknown>,
  returnUndefinedIfNone?: boolean
): string | undefined {
  if (!fileContentMap || fileContentMap.size === 0)
    return returnUndefinedIfNone ? undefined : '* **Available Documents:**\n---None loaded---';
  const list = [...fileContentMap.keys()].map(n => `  * ${n}`).join('\n');
  return `* **Available Documents:**\n${list}`;
}

export async function getInvestigationTitle(geminiClient?: GeminiClient): Promise<string | undefined> {
  if (investigationTitle) return investigationTitle;
  if (geminiClient) return refreshInvestigationTitle(geminiClient);
  return undefined;
}

async function doPaperAnalysis(
  filesToAnalyse: Set<string>,
  fileMap:        Map<string, string>,
  geminiClient:   GeminiClient
): Promise<Map<string, PaperSummary>> {
  const results = new Map<string, PaperSummary>();
  const promptTemplate = await getAssetString('paper-analysis');

  const filesBlock = [...filesToAnalyse].map(fn =>
    `Filename: **${fn}**\n\`\`\`\n${fileMap.get(fn) ?? '[Content not found]'}\n\`\`\``
  ).join('\n\n');

  const prompt = await replaceRuntimePlaceholders(promptTemplate, {
    PreviousJSON:     '--No previously processed data--',
    DocumentNameList: getDocumentListString(fileMap, false) ?? '* **Available Documents:**\n---None---',
    FilesForAnalysis: filesBlock,
  });

  let raw = (await geminiClient.sendOneShotMessage(prompt, { model: DEFAULT_GEMINI_LITE_MODEL }))?.text?.trim() ?? '';

  try {
    raw = removeBacktickFences(raw);
    const repaired = repairTruncatedJsonArray(raw);
    if (repaired) {
      const summaries: PaperSummary[] = JSON.parse(repaired);
      for (const s of summaries) {
        if (s.filename && typeof s.filename === 'string') results.set(s.filename, s);
      }
    }
  } catch (err: any) {
    console.error(`doPaperAnalysis: JSON parse failed: ${err.message}`, raw);
  }

  return results;
}

async function refreshInvestigationTitle(geminiClient: GeminiClient): Promise<string | undefined> {
  const existingHint = investigationTitle
    ? `We previously derived the investigation title '${investigationTitle}'. Return it if still appropriate, or a clearly better one.`
    : '';

  const descriptions = getPaperDescriptions();
  const context = descriptions
    ? `Here are the documents in this investigation:\n${descriptions}`
    : 'No documents are currently loaded.';

  const prompt = `I need a concise kebab-case identifier for this scientific-integrity investigation. ` +
    `Derive it from the document names, paper titles, or journal names present.\n\n${context}\n\n${existingHint}`.trimEnd();

  try {
    let result = (await geminiClient.sendOneShotMessage(prompt, { model: DEFAULT_GEMINI_LITE_MODEL }))?.text?.trim();
    if (result) {
      result = toKebabCase(removeBacktickFences(result));
      investigationTitle = result;
      return result;
    }
  } catch {}
  return undefined;
}

