

import { applyPatch, createTwoFilesPatch, parsePatch } from 'diff';
import { MultiAgentToolContext } from '../novum_core/types.js';
import { Buffer } from 'node:buffer';
import * as zlib from 'node:zlib';


const SUPPLEMENTARY_BINARY_EXTENSIONS = new Set([
  '.tif', '.tiff', '.png', '.jpg', '.jpeg', '.gif', '.bmp',
  '.raw', '.zip', '.tar', '.gz', '.7z',
  '.nii', '.nii.gz',   
  '.fcs',              
  '.czi', '.lif',      
]);


const AUTO_GENERATED_NAMES = new Set([
  'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml',
  'Cargo.lock', 'go.sum', 'poetry.lock',
]);

export function isSupplementaryBinary(filename: string): boolean {
  const ext = filename.slice(filename.lastIndexOf('.')).toLowerCase();
  return SUPPLEMENTARY_BINARY_EXTENSIONS.has(ext);
}

export function isAutoGenerated(filename: string): boolean {
  if (AUTO_GENERATED_NAMES.has(filename)) return true;
  const base = filename.split(/[/\\]/).pop() ?? '';
  return AUTO_GENERATED_NAMES.has(base);
}

export interface PaperVersionChanges {
  created:  string[];
  deleted:  string[];
  modified: string[];
  renamed:  { from: string; to: string }[];
  
  numericChanges: string[];
}


function detectNumericChanges(diffString: string): string[] {
  const suspiciousFiles: string[] = [];
  const fileHeaderRegex = /^diff --git a\/(.+) b\/(.+)$/gm;
  const numericLineRegex = /^[+-].*\b\d+\.?\d*\b/;

  let fileMatch: RegExpExecArray | null;
  while ((fileMatch = fileHeaderRegex.exec(diffString)) !== null) {
    const filename  = fileMatch[1];
    const nextMatch = fileHeaderRegex.exec(diffString);
    const segment   = diffString.slice(fileMatch.index, nextMatch?.index ?? diffString.length);
    fileHeaderRegex.lastIndex = nextMatch?.index ?? diffString.length;

    const changedLines = segment.split('\n').filter(l => numericLineRegex.test(l));
    if (changedLines.length > 0) suspiciousFiles.push(filename);
  }
  return [...new Set(suspiciousFiles)];
}


export function generatePaperDiff(
  originalFileMap:  Map<string, string>,
  revisedFileMap:   Map<string, string>,
  changedFilesSet:  Set<string>,
  binaryFiles:      Set<string>,
  redactBinaries:   boolean = false
): string {
  let fullDiff = '';
  const sortedFiles = Array.from(changedFilesSet).sort();

  for (const filename of sortedFiles) {
    const originalContent = originalFileMap.get(filename) ?? '';
    const revisedContent  = revisedFileMap.get(filename)  ?? '';
    const originalExists  = originalFileMap.has(filename);
    const revisedExists   = revisedFileMap.has(filename);

    if (originalContent === revisedContent && originalExists === revisedExists) continue;

    const isDeleted  = originalExists && !revisedExists;
    const isCreation = !originalExists && revisedExists;
    const isBinary   = binaryFiles.has(filename);
    const isAuto     = isAutoGenerated(filename);

    fullDiff += `diff --git a/${filename} b/${filename}\n`;
    if (isCreation) fullDiff += `new file mode 100644\n`;
    if (isDeleted)  fullDiff += `deleted file mode 100644\n`;

    if (isBinary && !isDeleted) {
      if (redactBinaries) {
        fullDiff += isCreation ? `--- /dev/null\n` : `--- a/${filename}\n`;
        fullDiff += `+++ b/${filename}\n`;
        fullDiff += `@@ -0,0 +1 @@\n+ [Supplementary binary � changes hidden; flag for image-integrity review]\n`;
      } else {
        fullDiff += `Binary files a/${filename} and b/${filename} differ\n`;
      }
      continue;
    }

    if (redactBinaries && isAuto) {
      fullDiff += isCreation ? `--- /dev/null\n` : `--- a/${filename}\n`;
      fullDiff += `+++ b/${filename}\n`;
      fullDiff += `@@ -0,0 +1 @@\n+ [Auto-generated file � diff hidden]\n`;
      continue;
    }

    const patch = createTwoFilesPatch(
      isCreation ? '/dev/null' : `a/${filename}`,
      isDeleted  ? '/dev/null' : `b/${filename}`,
      originalContent,
      revisedContent,
      '', '', { context: 3 }
    );

    const cleanPatch = patch
      .split('\n')
      .filter(line => !line.startsWith('==='))
      .join('\n');

    fullDiff += cleanPatch;
  }

  return fullDiff;
}


export function applyPaperDiff(
  fileMap:    Map<string, string>,
  diffString: string
): { success: boolean; changes?: PaperVersionChanges; error?: string } {
  try {
    const patches = parsePatch(diffString);
    const changes: PaperVersionChanges = {
      created: [], deleted: [], modified: [], renamed: [], numericChanges: [],
    };

    for (const patch of patches) {
      const isDeletion = patch.newFileName === '/dev/null';
      const isCreation = patch.oldFileName === '/dev/null';
      const filename = (isDeletion
        ? patch.oldFileName?.replace(/^a\//, '')
        : patch.newFileName?.replace(/^b\//, ''));

      if (!filename) return { success: false, error: 'Could not determine filename from patch.' };

      if (isDeletion) {
        fileMap.delete(filename);
        changes.deleted.push(filename);
        continue;
      }

      if (isCreation) {
        const newContent = applyPatch('', patch, { fuzzFactor: 4 });
        if (newContent === false) return { success: false, error: `Failed to apply creation patch to '${filename}'.` };
        fileMap.set(filename, newContent);
        changes.created.push(filename);
        continue;
      }

      const oldFilename = patch.oldFileName?.replace(/^a\//, '') ?? '';
      const originalContent = fileMap.get(oldFilename) ?? '';
      const newContent      = applyPatch(originalContent, patch, { fuzzFactor: 4 });

      if (newContent === false) return { success: false, error: `Failed to apply patch to '${oldFilename}'.` };

      fileMap.set(filename, newContent);
      if (oldFilename !== filename) {
        fileMap.delete(oldFilename);
        changes.renamed.push({ from: oldFilename, to: filename });
      } else {
        changes.modified.push(filename);
      }
    }

    changes.numericChanges = detectNumericChanges(diffString);
    return { success: true, changes };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error applying diff.';
    return { success: false, error: message };
  }
}


export function generatePaperDiffReport(context: MultiAgentToolContext, redactBinaries = false): string {
  const binaryPlaceholder = '[binary content]';
  const combinedOriginal = new Map<string, string>([
    ...(context.originalFileMap ?? new Map()),
    ...Array.from(context.originalBinaryFileMap?.keys() ?? []).map(k => [k, binaryPlaceholder] as [string, string]),
  ]);
  const combinedRevised = new Map<string, string>([
    ...context.fileMap,
    ...Array.from(context.binaryFileMap.keys()).map(k => [k, binaryPlaceholder] as [string, string]),
  ]);
  const allBinary = new Set([
    ...(context.originalBinaryFileMap?.keys() ?? []),
    ...context.binaryFileMap.keys(),
  ]);

  let diffString = generatePaperDiff(combinedOriginal, combinedRevised, context.editedFilesSet, allBinary, redactBinaries);
  if (!diffString) diffString = '---No changes detected between paper versions.---';

  let header = `# Paper Version Diff\nThe following diff tracks all changes between paper versions under investigation.`;
  if (redactBinaries) header += `\nNote: Supplementary binary files (images, data archives) are redacted; flag them for separate image-integrity analysis.`;

  return `${header}\n---Start of Version Diff---\n${diffString}\n---End of Version Diff---`;
}


export function decodeGitBinaryPatch(patchText: string): Buffer | null {
  const lines = patchText.split('\n');
  const dataLines: string[] = [];
  let inLiteral = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('literal')) {
      if (inLiteral && dataLines.length > 0) break;
      inLiteral = true;
      continue;
    }
    if (inLiteral && !trimmed) break;
    if (inLiteral) dataLines.push(trimmed);
  }

  if (dataLines.length === 0) return null;

  const alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+-;<=>?@^_`{|}~';
  const charMap: Record<string, number> = {};
  for (let i = 0; i < alphabet.length; i++) charMap[alphabet[i]] = i;

  const buffers: Buffer[] = [];
  for (const line of dataLines) {
    if (!line.length) continue;
    const fc = line.charCodeAt(0);
    let bytesInLine = 0;
    if (fc >= 65 && fc <= 90)  bytesInLine = fc - 65 + 1;
    else if (fc >= 97 && fc <= 122) bytesInLine = fc - 97 + 27;
    else continue;

    const encoded   = line.substring(1);
    const lineBuf   = Buffer.alloc(bytesInLine);
    let outIdx      = 0;

    for (let i = 0; i < encoded.length && outIdx < bytesInLine; i += 5) {
      let acc = 0;
      for (let j = 0; j < 5; j++) {
        acc = acc * 85 + (charMap[encoded[i + j] || '}'] ?? 0);
      }
      for (let shift = 24; shift >= 0 && outIdx < bytesInLine; shift -= 8) {
        lineBuf[outIdx++] = (acc >> shift) & 0xff;
      }
    }
    buffers.push(lineBuf);
  }

  try { return zlib.inflateSync(Buffer.concat(buffers)); }
  catch (e) { console.error('Failed to inflate git binary patch:', e); return null; }
}

export function isLockFile(filename: string): boolean {
  return filename.endsWith('package-lock.json') || filename.endsWith('yarn.lock') || filename.endsWith('Cargo.lock') || filename.endsWith('go.sum');
}

export function getLockFileHiddenPlaceholder(filename: string): string {
  return `--- Content of auto-generated lock file '${filename}' hidden ---`;
}

